import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// const socket = io();
import { io } from "socket.io-client";

export default function Home() {
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css"
          integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk="
          crossorigin="anonymous"
        />
        <link rel="stylesheet" href="css/style.css" />
        <title>ChatCord App</title>
      </head>
      <body>
        <div class="chat-container">
          <header class="chat-header">
            <h1><i class="fas fa-smile"></i> ChatCord</h1>
            <a id="leave-btn" class="btn">Leave Room</a>
          </header>
          <main class="chat-main">
            <div class="chat-sidebar">
              <h3><i class="fas fa-comments"></i> Room Name:</h3>
              <h2 id="room-name"></h2>
              <h3><i class="fas fa-users"></i> Users</h3>
              <ul id="users"></ul>
            </div>
            <div class="chat-messages"></div>
          </main>
          <div class="chat-form-container">
            <form id="chat-form">
              <input
                id="msg"
                type="text"
                placeholder="Enter Message"
                required
                autocomplete="off"
              />
              <button class="btn"><i class="fas fa-paper-plane"></i> Send</button>
            </form>
          </div>
        </div>

        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/qs/6.9.2/qs.min.js"
          integrity="sha256-TDxXjkAUay70ae/QJBEpGKkpVslXaHHayklIVglFRT4="
          crossorigin="anonymous"
        ></script>
        {/* <script src="/socket.io/socket.io.js"></script>
        <script> const socket = io(); <script> */}
        {/* <script src="js/main.js"></script> */}
      </body>
    </html>
}

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
